---
title: "ThermalBuffer_Script"
output:
  word_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Data wrangling packages
library(tidyverse)
library(dplyr)
library(ggplot2)
library(lubridate)
library(patchwork)
library(astsa)
library(weathermetrics)
library(report)
library(car)
library(multcomp)
library(MetBrewer)

# Time series analysis packages
library(MARSS)
library(MASS)
library(forecast)
library(zoo)
library(imputeTS) 
```
#Hourly Data
###Data Wrangling
```{r}
#Read in data
quarterHour_condensed <- readRDS('quarterHour_condensed.RDS')
quarterHour_condensed <- as.data.frame(t(quarterHour_condensed))
quarterHour_condensed <- quarterHour_condensed %>% mutate_all(~ifelse(is.nan(.), NA, .))

#Create 15 min sequence
quarterHour <- seq(mdy_h('7/1/2020 00'),mdy_h('7/13/2021 00'),by = "15 mins")
quarterHour <- as.data.frame(quarterHour)

#Attach to data frame
quarterHour_condensed <- cbind(quarterHour_condensed,quarterHour)

#Format data long
quarterHour_long <- gather(quarterHour_condensed, site, value, -quarterHour)
```

#Seasonal buffering
##Summer 
###Data wrangling
```{r}
#Read in data
daily_maxs_condensed <- readRDS('daily_maxs_condensed.RDS')
daily_maxs_condensed <- as.data.frame(t(daily_maxs_condensed))
daily_maxs_condensed <- daily_maxs_condensed %>% mutate_all(~ifelse(is.nan(.), NA, .))

#Create "day" sequence 
day <- seq(mdy('7/1/2020'),mdy('7/13/2021'),by = "day") 
day <- as.data.frame(day) #convert "day" to data frame

#Attach day to data frame
daily_maxs_condensed <- cbind(daily_maxs_condensed,day)

#Format data long
daily_max_long <- gather(daily_maxs_condensed, site, value, -day)
data_summer <- daily_max_long %>%filter(day>'2020-07-15'& day < '2020-09-15')
```

###Seiad Creek 
```{r}
#Boxplot
b1 <- ggplot(subset(data_summer, site %in% c("AP","SP","Durazo","LS","May","SC")))+
  geom_boxplot(aes(x = site, value, col = day))+
  labs(title = "(a) Seiad Creek, 15 July - 15 September")+
  theme_classic()+
  theme(text=element_text(size=16), axis.title.x=element_blank())+
  scale_x_discrete(name ="Site", 
                   limits = c("AP","SP","Durazo","LS","May","SC"),
                    labels=c("AP" = "Alexander","SP"= "Stender","Durazo"=
                               "Durazo","LS" = "LowerSeiad","May"="May","SC" = "SeiadCreek"))+
  scale_y_continuous(name="Daily Maximum Temp (C)",limits=c(12.5, 22.5))


#ANOVA
data_summer_SC <- subset(data_summer, site %in% c("AP","SP","Durazo","LS","May","SC"))
shapiro.test(data_summer_SC$value) #check for normality
leveneTest(value ~ site, data = data_summer_SC) #check for equal variances
anova_SC <- aov(value ~ site, data = data_summer_SC) #run one way anova
summary.aov(anova_SC)
TukeyHSD(anova_SC) #posthoc analysis
report(anova_SC)
```

###Horse Creek
```{r}
#Boxplot
b2 <- ggplot(subset(data_summer, site %in% c("FG","UL","LL","GP","HC")))+
  geom_boxplot(aes(x = site, value, col = day))+
  labs(title = "(b) Horse Creek, 15 July - 15 September")+
  theme_classic()+
  theme(text=element_text(size=16), axis.title.x=element_blank())+
  scale_x_discrete(name ="Site", 
                   limits = c("FG","UL","LL","GP","HC"),
                    labels=c("FG" = "FishGulch","UL"= "UpperLaw","LL"=
                               "LowerLaw","GP" = "Goodman","HC"="HorseCreek"))+
  scale_y_continuous(name="Daily Maximum Temp (C)",limits=c(12.5, 22.5))

#ANOVA
data_summer_HC <- subset(data_summer, site %in% c("FG","UL","LL","GP","HC"))
shapiro.test(data_summer_HC$value) #check for normality
leveneTest(value ~ site, data = data_summer_HC) #check for equal variances
anova_HC <- aov(value ~ site, data = data_summer_HC) #run one way anova
summary.aov(anova_HC)
TukeyHSD(anova_HC) #posthoc analysis
report(anova_HC)
```

##Winter 
###Data wrangling
```{r}
#Read in data
daily_mins_condensed <- readRDS('daily_mins_condensed.RDS')
daily_mins_condensed <- as.data.frame(t(daily_mins_condensed))
daily_mins_condensed <- daily_mins_condensed %>% mutate_all(~ifelse(is.nan(.), NA, .))

#Create "day" sequence 
day <- seq(mdy('7/1/2020'),mdy('7/13/2021'),by = "day") 
day <- as.data.frame(day) #convert "day" to data frame

#Attach day to data frame
daily_mins_condensed <- cbind(daily_mins_condensed,day)

#Format data long
daily_min_long <- gather(daily_mins_condensed, site, value, -day)
data_winter <- daily_min_long %>%filter(day>'2020-12-15'& day < '2021-02-15')
```

###Seiad Creek 
```{r}
#Boxplot
b3 <- ggplot(subset(data_winter, site %in% c("AP","SP","Durazo","LS","May","SC")))+
  geom_boxplot(aes(x = site, value, col = day))+
  labs(title = "(c) Seiad Creek, 15 December - 15 February")+
  theme_classic()+
  theme(text=element_text(size=16))+
  scale_x_discrete(name ="Site", 
                   limits = c("AP","SP","Durazo","LS","May","SC"),
                    labels=c("AP" = "Alexander","SP"= "Stender","Durazo"=
                               "Durazo","LS" = "LowerSeiad","May"="May","SC" = "SeiadCreek"))+
  scale_y_continuous(name="Daily Minimum Temp (C)",limits=c(4, 12))

#ANOVA
data_winter_SC <- subset(data_winter, site %in% c("AP","SP","Durazo","LS","May","SC"))
shapiro.test(data_winter_SC$value) #check for normality
leveneTest(value ~ site, data = data_winter_SC) #check for equal variances
#variances not equal, need to transform
data_winter_SC$trans <- log(data_winter_SC$value)
leveneTest(trans ~ site, data = data_winter_SC)
#variances equal with log transformation

anova_SC2 <- aov(trans ~ site, data = data_winter_SC) #run one way anova
summary.aov(anova_SC2)
TukeyHSD(anova_SC2) #posthoc analysis
report(anova_SC2)

```

###Horse Creek
```{r}
#Boxplot
b4 <- ggplot(subset(data_winter, site %in% c("FG","UL","LL","GP","HC")))+
  geom_boxplot(aes(x = site, value, col = day))+
  labs(title = "(d) Horse Creek, 15 December - 15 February")+
  theme_classic()+
  theme(text=element_text(size=16))+
  scale_x_discrete(name ="Site", 
                   limits = c("FG","UL","LL","GP","HC"),
                    labels=c("FG" = "FishGulch","UL"= "UpperLaw","LL"=
                               "LowerLaw","GP" = "Goodman","HC"="HorseCreek"))+
  scale_y_continuous(name="Daily Minimum Temp (C)",limits=c(4, 12))

#ANOVA
data_winter_HC <- subset(data_winter, site %in% c("FG","UL","LL","GP","HC"))
shapiro.test(data_winter_HC$value) #check for normality
leveneTest(value ~ site, data = data_winter_HC) #check for equal variances
anova_HC2 <- aov(value ~ site, data = data_winter_HC) #run one way anova
summary.aov(anova_HC2)
TukeyHSD(anova_HC2) #posthoc analysis
report(anova_HC2)
```
##Boxplot Figure
```{r}
png("Fig_Boxplots.png",width = 1000, height = 600)
(b1 + b2) / (b3 + b4)
dev.off()
```

#Daily Buffering
##Data wrangling
```{r}
quarterHour_condensed$day <- lubridate::floor_date(quarterHour_condensed$quarterHour, unit="day") #Bin by day

#Create a function for coefficient of variance (CV)
CV <- function(x){
        (sd(x)/mean(x))*100
}
```

##Individual CVs
```{r}
#Alexander Pond 
AP_CV <- quarterHour_condensed %>%       #15 min data
  group_by(day) %>%                      #Group by day
  dplyr::select(AP) %>%                  #Select site
  summarize(CV = CV(AP))                 #Calculate CV per day for one site
AP_CV_mean <- mean(AP_CV$CV,na.rm=T)     #Take all days as mean over entire year
plot(AP_CV$day,AP_CV$CV)                 #Plot a time series of CV

#Stender Pond
SP_CV <- quarterHour_condensed %>% 
  group_by(day) %>% 
  dplyr::select(SP) %>%
  summarize(CV = CV(SP))
SP_CV_mean <- mean(SP_CV$CV,na.rm=T)
plot(SP_CV$day,SP_CV$CV)

#Durazo Pond
Durazo_CV <- quarterHour_condensed %>% 
  group_by(day) %>% 
  dplyr::select(Durazo) %>%
  summarize(CV = CV(Durazo))
Durazo_CV_mean <- mean(Durazo_CV$CV,na.rm=T)
plot(Durazo_CV$day,Durazo_CV$CV)

#Lower Seiad 
LS_CV <- quarterHour_condensed %>% 
  group_by(day) %>% 
  dplyr::select(LS) %>%
  summarize(CV = CV(LS))
LS_CV_mean <- mean(LS_CV$CV,na.rm=T)
plot(LS_CV$day,LS_CV$CV)

#May Pond
May_CV <- quarterHour_condensed %>% 
  group_by(day) %>% 
  dplyr::select(May) %>%
  summarize(CV = CV(May))
May_CV_mean <- mean(May_CV$CV,na.rm=T)
plot(May_CV$day,May_CV$CV)

#Fish Gulch
FG_CV <- quarterHour_condensed %>% 
  group_by(day) %>% 
  dplyr::select(FG) %>%
  summarize(CV = CV(FG))
FG_CV_mean <- mean(FG_CV$CV,na.rm=T)
plot(FG_CV$day,FG_CV$CV)

#Goodman Pond
GP_CV <- quarterHour_condensed %>% 
  group_by(day) %>% 
  dplyr::select(GP) %>%
  summarize(CV = CV(GP))
GP_CV_mean <- mean(GP_CV$CV,na.rm=T)
plot(GP_CV$day,GP_CV$CV)

#Upper Lawrence
UL_CV <- quarterHour_condensed %>% 
  group_by(day) %>% 
  dplyr::select(UL) %>%
  summarize(CV = CV(UL))
UL_CV_mean <- mean(UL_CV$CV,na.rm=T)
plot(UL_CV$day,UL_CV$CV)

#Lower Lawrence
LL_CV <- quarterHour_condensed %>% 
  group_by(day) %>% 
  dplyr::select(LL) %>%
  summarize(CV = CV(LL))
LL_CV_mean <- mean(LL_CV$CV,na.rm=T)
plot(LL_CV$day,LL_CV$CV)

#Seiad Creek
SC_CV <- quarterHour_condensed %>% 
  group_by(day) %>% 
  dplyr::select(SC) %>%
  summarize(CV = CV(SC))
SC_CV_mean <- mean(SC_CV$CV,na.rm=T)
plot(SC_CV$day,SC_CV$CV)

#Horse Creek
HC_CV <- quarterHour_condensed %>% 
  group_by(day) %>% 
  dplyr::select(HC) %>%
  summarize(CV = CV(HC))
HC_CV_mean <- mean(HC_CV$CV,na.rm=T)
plot(HC_CV$day,HC_CV$CV)

```

##CV Ratios
```{r}
#CV Ratios are Creeks/Ponds
#No Buffering = <1
#Buffering = >1

#Alexander Pond 
SC_AP <- SC_CV_mean/AP_CV_mean

#Stender Pond
SC_SP <- SC_CV_mean/SP_CV_mean

#Durazo Pond
SC_Durazo <- SC_CV_mean/Durazo_CV_mean

#Lower Seiad 
SC_LS <- SC_CV_mean/LS_CV_mean

#May Pond
SC_May <- SC_CV_mean/May_CV_mean

#Fish Gulch
HC_FG <- HC_CV_mean/FG_CV_mean

#Goodman Pond
HC_GP <- HC_CV_mean/GP_CV_mean

#Upper Lawrence
HC_UL <- HC_CV_mean/UL_CV_mean

#Lower Lawrence
HC_LL <- HC_CV_mean/LL_CV_mean
```

##CV Data Table
```{r}
data.frame(Creek=c("Seiad Creek","Seiad Creek","Seiad Creek","Seiad Creek","Seiad Creek","Horse Creek","Horse Creek","Horse Creek","Horse Creek"),
           CreekCV=round(c(SC_CV_mean,SC_CV_mean,SC_CV_mean,SC_CV_mean,SC_CV_mean,HC_CV_mean,HC_CV_mean,HC_CV_mean,HC_CV_mean),2),
           Pond=c("Alexander","Stender","Durazo","Lower Seiad","May","Fish Gulch","Goodman","Upper Lawrence","Lower Lawrence"),
           PondCV=round(c(AP_CV_mean,SP_CV_mean,Durazo_CV_mean,LS_CV_mean,May_CV_mean,FG_CV_mean,GP_CV_mean,UL_CV_mean,LL_CV_mean),2),
           CV_Ratio=(round(c(SC_AP, 
                        SC_SP,
                        SC_Durazo,
                        SC_LS,
                        SC_May,
                        HC_FG,
                        HC_GP,
                        HC_UL,
                        HC_LL),2)))

```
#Figure 3: Time Series Examples Figure
```{r}

daily_means_condensed <- readRDS('daily_means_condensed.RDS')
daily_means_condensed <- as.data.frame(t(daily_means_condensed))
daily_means_condensed <- daily_means_condensed %>% mutate_all(~ifelse(is.nan(.), NA, .))
day <- seq(mdy('7/1/2020'),mdy('7/13/2021'),by = "day") 
day <- as.data.frame(day) #convert "day" to data frame

#Attach day to data frame
daily_means_condensed <- cbind(daily_means_condensed,day)
daily_means_condensed$day <- as.POSIXct(daily_means_condensed$day)

mycolors <- met.brewer(name="Archambault",n=4,type="discrete")

p1 <- ggplot()+
  geom_line(data = quarterHour_condensed, aes(x = quarterHour, y = AP), color ="#D3D3D3", size = 1) +
  geom_line(data = daily_means_condensed, aes(x = day, y = AP), color ="#88a0dc", size = 1) +
  labs(title = "(a) Alexander Pond", x = "Date", y = "Temperature (C)")+
  scale_y_continuous(name="Daily Mean Temp (C)",limits=c(0, 25))+
  theme_classic()+
  theme(text=element_text(size=16),legend.position = "none",axis.title.x=element_blank())
p2 <- ggplot()+
  geom_line(data = quarterHour_condensed, aes(x = quarterHour, y = UL), color ="#D3D3D3", size = 1) +
  geom_line(data = daily_means_condensed, aes(x = day, y = UL), color = "#ed968c", size = 1) +
  labs(title = "(c) Upper Lawrence Pond", x = "Date", y = "Temperature (C)")+
  scale_y_continuous(name="Daily Mean Temp (C)",limits=c(0, 25))+
  theme_classic()+
  theme(text=element_text(size=16),legend.position = "none")
p3 <- ggplot()+
  geom_line(data = quarterHour_condensed, aes(x = quarterHour, y = SC), color ="#D3D3D3", size = 1) +
  geom_line(data = daily_means_condensed, aes(x = day, y = SC), color = "#e78429", size = 1) +
  labs(title = "(b) Seiad Creek", x = "Date", y = "Temperature (C)")+
  scale_y_continuous(name="Daily Mean Temp (C)",limits=c(0, 25))+
  theme_classic()+
  theme(text=element_text(size=16),legend.position = "none", axis.title.x=element_blank())
p4 <- ggplot()+
  geom_line(data = quarterHour_condensed, aes(x = quarterHour, y = HC), color ="#D3D3D3", size = 1) +
  geom_line(data = daily_means_condensed, aes(x = day, y = HC), color = "#f9d14a", size = 1) +
  labs(title = "(d) Horse Creek", x = "Date", y = "Temperature (C)")+
  scale_y_continuous(name="Daily Mean Temp (C)",limits=c(0, 25))+
  theme_classic()+
  theme(text=element_text(size=16),legend.position = "none")

png("Fig_TempTimeSeries.png",width = 1000, height = 600)
(p1 + p3) / (p2 + p4)
dev.off()


```
#May Pond Example
```{r}
May <- readRDS("May.rds")
MayCk <- readRDS("MayCk.rds")

May_August <-May %>%filter(day>'2020-08-01'& day < '2020-08-31')
May_August <- May_August[,c("Temp","date")]         
MayCk_August <-MayCk %>%filter(day>'2020-08-01'& day < '2020-08-31')
MayCk_August <- MayCk_August[,c("Temp","date")] 

png("Fig_MayPond.png", width = 700, height = 400)
ggplot()+
  geom_line(data = May_August, aes(x = date, y = Temp, color = "May Pond"))+
  geom_line(data = MayCk_August, aes(x = date, y = Temp, color = "Seiad Creek"))+
  labs(x = "Date",
       y = "Hourly Temperature (C)",
       title = "May Pond and Seiad Creek, August 2020")+
  theme_classic()+
  theme(text=element_text(size=16), legend.position = "bottom")+
  scale_colour_manual("", values = c("May Pond"="#88a0dc", "Seiad Creek"="#ed968c")) +
  scale_y_continuous("Hourly Temperature (C)") 
dev.off()
```

